### ISSUE TITLE
Additional information for reproducing results on ActivityNet v1.3

### ISSUE THREAD

**Issue by HyunwooKims** [lgzlIlIlI/Boosting-WTAL#3]
Thanks for the great work and releasing the codes.

I have some questions during reproducing your results on ActivityNet v1.3

---

1. As I read your paper, I checked that not all configurations(hyperparameters) are specified.
So if possible, can you provide us the **'options.py' for ANet v1.3 dataset**?

2. As an extra question, the 'vocab.pkl' file that you provided does not contain some of class words in ANet v1.3. (e.g. "slacklining", "powerboking")
Where can we get the **GloVe feature of those words you used**?

Thank you very much for your time.

**Comment by lgzlIlIlI** [comment]
hi, I have uploaded the code and files required for training on the Anet13 dataset.

**Comment by ydwl-lynn** [comment]
Thank you very much!

**Comment by HyunwooKims** [comment]
Thanks for the Code release!
