### ISSUE TITLE
Problems with running the ActivityNet dataset

### ISSUE THREAD

**Issue by ydwl-lynn** [lgzlIlIlI/Boosting-WTAL#4]
when I run the code "bash Anetrun.sh". The program reports the following error:
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    result_file = open('/data/lgz/originalANET13/result_1007/'+result_path,'w')
FileNotFoundError: [Errno 2] No such file or directory: '/data/lgz/originalANET13/result_1007/NEW0.01pos_MSE0.25_OURATTDrop0.7_Trans_vidDrop0.5_thb0.15'
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    result_file = open('/data/lgz/originalANET13/result_1007/'+result_path,'w')
FileNotFoundError: [Errno 2] No such file or directory: '/data/lgz/originalANET13/result_1007/NEW0.01pos_MSE0.25_OURATTDrop0.7_Trans_vidDrop0.5_thb0.15'
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    result_file = open('/data/lgz/originalANET13/result_1007/'+result_path,'w')
FileNotFoundError: [Errno 2] No such file or directory: '/data/lgz/originalANET13/result_1007/NEW0.01pos_MSE0.25_OURATTDrop0.7_Trans_vidDrop0.5_thb0.15'
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    result_file = open('/data/lgz/originalANET13/result_1007/'+result_path,'w')
FileNotFoundError: [Errno 2] No such file or directory: '/data/lgz/originalANET13/result_1007/NEW0.01pos_MSE0.25_OURATTDrop0.7_Trans_vidDrop0.5_thb0.15'
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    result_file = open('/data/lgz/originalANET13/result_1007/'+result_path,'w')
FileNotFoundError: [Errno 2] No such file or directory: '/data/lgz/originalANET13/result_1007/NEW0.01pos_MSE0.25_OURATTDrop0.7_Trans_vidDrop0.5_thb0.15'

**Comment by lgzlIlIlI** [comment]
hi, You should change the paths of all files to your own local paths

**Comment by mymuli** [comment]
Hello! 
May I ask how to obtain the ActivityNe v1.3 dataset?
